function randomMessage() {
	var text
	var x = Math.round(Math.random()*49)

	if (x == 0) text =  "Everyone lies, but it doesn't matter.</BR>Nobody listens."
	if (x == 1) text =  "Glory is fleeting, but obscurity is forever."
	if (x == 2) text =  "Some call it laziness,</BR>I call it deep thought."
	if (x == 3) text =  "When you stop to think,</BR>don't forget to start again."
	if (x == 4) text =  "To be great is to be misunderstood."
	if (x == 5) text =  "Better to understand little</BR>than to misunderstand a lot."
	if (x == 6) text =  "How you look depends on where you go."
	if (x == 7) text =  "Nothing is foolproof...</BR>fools are very clever."
	if (x == 8) text =  "Due to lack of interest,</BR>today has been cancelled."
	if (x == 9) text =  "A conclusion is where you got tired of thinking."
	if (x == 10) text = "Everybody has a photographic memory...</BR>Some don't have film."
	if (x == 11) text = "Few women admit their age. Few men act theirs."
	if (x == 12) text = "Everybody wants to go to heaven,</BR>but nobody wants to die."
	if (x == 13) text = "To know you have enough is to be rich. </BR> --- Tao"
	if (x == 14) text = "Every exit is an entrance somewhere else. </BR> --- Tom Stoppard"
	if (x == 15) text = "Reality is for people who lack the imagination."
	if (x == 16) text = "If the facts don't fit the theory, change the facts. </BR> --- Albert Einstein"
	if (x == 17) text = "Education's purpose is to replace an empty mind with an open one. </BR> --- Malcolm S. Forbes"
	if (x == 18) text = "I have too much respect for the idea of God </BR> to make it responsible for such an absurd world. </BR> --- Georges Duhamel"
	if (x == 19) text = "An intellectual is a man who takes more words </BR> than necessary to tell more than he knows. </BR> --- Dwight D. Eisenhower"
	if (x == 20) text = "He who hesitates is not only lost, but miles from the next exit."
	if (x == 21) text = "The opposite of a correct statement is a false statement. </BR> But the opposite of a profound truth may well be </BR> another profound truth. </BR> --- Niels Bohr"
	if (x == 22) text = "information is free. </BR> the only question is: </BR> are you? </BR> 	(from draves.org)"
	if (x == 23) text = "Formerly, when religion was strong and science weak, </BR> men mistook magic for medicine; </BR> now, when science is strong and religion weak, </BR> men mistake medicine for magic. </BR> --- Thomas Szasz"
	if (x == 24) text = "Believe those who are seeking the truth. </BR> Doubt those who find it. </BR> --- Andre Gide"
	if (x == 25) text = "Laziness is nothing more than the habit </BR> of resting before you get tired. </BR> --- Jules Renard"
	if (x == 26) text = "Don't you wish there were a knob on the </BR> TV to turn up the intelligence? There's one marked </BR> 'Brightness', but it doesn't work. </BR> --- Gallagher"
	if (x == 27) text = "The surest sign that intelligent life exists elsewhere </BR> in the universe is that it has never tried to contact us. </BR> --- Calvin and Hobbes (Bill Watterson)"
	if (x == 28) text = "Life is something that happens when you can't get to sleep. </BR> --- Fran Lebowitz"
	if (x == 29) text = "Eternity's a terrible thought. </BR> I mean, where's it all going to end? </BR> --- Tom Stoppard, _Rosencrantz and Guildenstern are Dead_"
	if (x == 30) text = "Well, if crime fighters fight crime and fire fighters fight </BR> fire, what do freedom fighters fight? They never mention </BR> that part to us, do they? </BR> --- George Carlin"
	if (x == 31) text = "To you I'm an atheist; to God, I'm the Loyal Opposition. </BR> --- Woody Allen"
	if (x == 32) text = "Maybe this world is another planet's hell. </BR> --- Aldous Huxley"
	if (x == 33) text = "You can go a long way with a smile. </BR> You can go a lot farther with a smile and a gun. </BR> --- Al Capone"
	if (x == 34) text = "My doctor told me to stop having intimate dinners for four. </BR> Unless there are three other people. </BR> --- Orson Welles"
	if (x == 35) text = "If you believe everything you read, better not read."
	if (x == 36) text = "My life has a superb cast but I can't figure out the plot. </BR> --- Ashleigh Brilliant"
	if (x == 37) text = "There are two major products that come out of Berkeley: LSD and UNIX. </BR> We don't believe this to be a coincidence. </BR> --- Jeremy S. Anderson"
	if (x == 38) text = "Always remember that you are unique. </BR> Just like everyone else."
	if (x == 39) text = "HARDWARE, n.: </BR> The parts of a computer system that can be kicked."
	if (x == 40) text = "Life would be so much easier if we could just look at the source code."
	if (x == 41) text = "USER, n.: </BR> The word computer professionals use when they mean 'idiot'."
	if (x == 42) text = "Human colonization of cyberspace so far seems to be equivalent of </BR> landing on the moon and setting up a McDonalds and a strip show."
	if (x == 43) text = "Teamwork is essential - it allows you to blame someone else."
	if (x == 44) text = "Having sex on the first date does not make me 'easy' </BR>       ...it just makes me 'user friendly.' "
	if (x == 45) text = "Man is ready to die for an idea, provided that idea </BR> is not quite clear to him. </BR> --- Paul Eldridge (Horns of Glass)"
	if (x == 46) text = "All we see or seem is just a dream within a dream. </BR> --- A.E.Poe"
    if (x == 47) text = "Do not condemn the judgement of another because it </BR> differs from your own. You may both be wrong. </BR> --- Dandemis"
    if (x == 48) text = "Wise men talk because they have something to say; </BR> fools, because they have to say something. </BR> --- Plato"
    if (x == 49) text = "TV Hero will never die!</BR>Rather play chess! (from web4096 compo)"

	return text
  }